language: c++

branches:
  only: master

before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa > /dev/null 2>&1
  - sudo apt-get -qq update
  - sudo apt-get install -y qt5-qmake qtbase5-dev qtdeclarative5-dev qt5-default qttools5-dev-tools

script:
  - qmake network-clipboard.pro -r -spec linux-g++
  - make

deploy:
  provider: releases
  api-key: 

notifications:
  email:
    on_success: never
    on_failure: never
