language: c++

branches:
  only: master

before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa > /dev/null 2>&1
  - sudo apt-get -qq update
  - sudo apt-get install -y qtdeclarative5-dev

script: qmake network-clipboard.pro -r -spec linux-g++

notifications:
  email:
    on_success: never
    on_failure: never
