dist: trusty
sudo: required

language: c++

branches:
  only: master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq qtchooser qt5-qmake qt5-default qtbase5-dev libqt5gui5 libqt5quick5 libqt5qml5 qtdeclarative5-dev qtdeclarative5-qtquick2-plugin

env:
  - QT_SELECT=5

script:
  - qmake network-clipboard.pro -r -spec linux-g++
  - make

deploy:
  provider: releases
  api_key:
    secure: 4jROVvgWZF6agj7nZDePz0+KR6GbTfuHWQKezldnDC7BSpeXKAix+mLQBix/1S3ddFv0Lb01sVmafliErarmrzsgBE6bQx1yVpUmDPU6/LLFfqtQ/MUfdGGxSHIrEBBlrJfj3JrLIk6b4bTz04M7BwnHCfnhTGFSrZtH1/HKlfISoUZdxw+4a91vuaJTr7p13ZViXGv8S+7eCN0FvQCu/qXZAwAMFD+cvY5WJqQ5I+WaR1b1yu1vHDiAR+X7Fw70RuIwt0udhpwV9XyK2+3ArMfPNgFgadtB/x900j4d9Cz6FFbflClJBzz48h/ltIGP0N4GvXN8ea0u2DkCn33on2kuJI6r9CJ1cLkgq6009YqvjYuseLmA5zh7YqA4MgNmMxhri4Fk1wrxf0fA1Ip3zro4ykbTksjMxg121OnOXrEKGb64TEK8YIn8sHTE5mPeN2rMEBajSn+t9tmPTnjqB7afjZswi2CEtpAsNJ9wMvq2G0yPORQaGjnk7ye5J6EcUMNJLNgmG0w9s5OQPmzPHsm8qa4h70A43t1qWy+8Q51LTJ0318Qf2SAMOFmH9RBP17cK31fYM2GDpePKDvlNr0O4Mz5ByOkqWFmcfNKgJoukVLwXqv5j+7RJG3UG1mU9BBSaZHkdL7T6+lXXTXXBcggRxIPld9zUGt3ZVrXe1Mc=
  file: bin/network-clipboard
  on:
    repo: tostiheld/network-clipboard

notifications:
  email:
    on_success: never
    on_failure: never
